import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Link from 'next/link'
import { Flex, Box, Text, Button } from '@chakra-ui/react'
import { api_base_url, fetchApi } from 'util/rapidApi'
import axios from 'axios'
import { Movie } from 'components/Movie'

const inter = Inter({ subsets: ['latin'] })

const Banner = ({ purpose, imageURL, title1, title2, description1, buttonText, linkName}) => (
  <Flex flexWrap="wrap" flexDirection="row" justifyContent="center" alignItems="center" m={10}>
    <Image src={imageURL} height={300} width={500} alt="banner-alt"/>
    <Box p={5}>
      <Text color="gray" fontSize="md" fontWeight="medium"> {purpose} </Text>
      <Text fontSize="xl" fontWeight="extrabold"> {title1} <br /> {title2} </Text>
      <Text color="gray.800" fontSize="lg" paddingTop="3" paddingBottom={3} fontWeight="normal"> {description1} </Text>
      <Button fontSize="xl" bg="gray" color="white">
        <Link href={linkName}>{buttonText}</Link>
      </Button>
    </Box>
  </Flex>
)

export default function Home({ moviesToDisplay }) {
  console.log(moviesToDisplay)
  return (
    <>
      <Head>
        <title>Create App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner 
          purpose={'for sale'} 
          imageURL="https://i.natgeofe.com/k/59ccd67f-c57c-4946-99bd-f957a38dafaa/hippopotamus-closeup-water_square.jpg" 
          title1="title1"
          title2="title2"
          description1="Explore our movies"
          buttonText="explore Horror"
          linkName="/search?purpose=for-rent"
        />
        <Flex flexWrap="wrap" p={3} background="facebook.200" >
          {moviesToDisplay.results.map((movie) => 
            <Movie movie={movie} key={movie.id}> SHIT </Movie>
          )}
        </Flex>

        <Banner 
          purpose={'for sale'} 
          imageURL="https://i.natgeofe.com/k/59ccd67f-c57c-4946-99bd-f957a38dafaa/hippopotamus-closeup-water_square.jpg" 
          title1="title1"
          title2="title2"
          description1="Explore our movies"
          buttonText="explore Horror"
          linkName="/search?purpose=for-rent"
        />
      </div>
      <Flex flexWrap="wrap" >
      </Flex>


      {/* <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>
        </div>
      </main> */}
    </>
  )
}

// this runs at build-time
export async function getStaticProps() {
  const moviesDataToDisplay = await fetchApi(`${api_base_url}/titles`)

  return {
    props: {
      moviesToDisplay: moviesDataToDisplay,
    }
  }
}